### ISSUE TITLE
date type

### ISSUE THREAD

**Issue by ericxin1982** [ovesco/flyter#1]
Hi @ovesco 

If I want to create a date type, how to start?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
I found answer, thanks.

**Comment by ovesco** [comment]
Hey sorry I was away, glad you found an answer. Just for precision did you want to use a native HTML date input or a custom javascript datepicker library?

**Comment by ericxin1982** [comment]
Hi, I think I just need a native html date input is enough. Thanks for asking.
