### ISSUE TITLE
attach element inside x-for loop, and filter change, x-for rerun, how about the attached element, what is the status?

### ISSUE THREAD

**Issue by ericxin1982** [ovesco/flyter#2]
Hi @ovesco 

I am trying to use this great library with alpine.js or vue3, and I am curious how about I attach it to element inside x-for loop, especially when filter change, and x-for occur, and dom element would be re-drawn.

I meant duplicated instance would be created or how it should look like?

thanks
Eric Xin

**Comment by ovesco** [comment]
Hello, that's a good question it's been a while since I started working on this library and can see a regain in interest regarding it.

I'm gonna do some tests today to see how to integrate it properly in react, vue and such and will come back to you later.

**Comment by ericxin1982** [comment]
Thanks so much!

**Comment by ovesco** [comment]
Hey,

So I went back into this library and updated some stuff.
Documentation is brand new, I added a few examples, including for alpine.

https://ovesco.github.io/flyter/examples/usage-with-alpine.html

**Comment by ericxin1982** [comment]
You are very awesome.

**Comment by ericxin1982** [comment]
HI @ovesco 

I read the code, and I have a question, if I have disabled the element, like your example, I disabled the "p" element, I can see it, but I cannot click and interact with it, how to achieve? Like normal way, or I have to set the logic inside the directive, please advise!

Thanks
Eric Xin

**Comment by ovesco** [comment]
Hi,

I published a new version with support for disabling a flyter instance.
I updated the doc and the Vuejs example to include it, mainly you can now call `instance.enable()` or `instance.disable()` for such behavior to happen.

**Comment by ericxin1982** [comment]
Hi @ovesco 

If I have 500 rows, and each row I have 10 cells, and I have to create 5000 instances, right?
Is that making dom heavy, and causing performance issue?

thanks
Eric Xin

**Comment by ovesco** [comment]
Flyter's DOM is not much in itself, it is dynamically added on open so just creating instances won't impact much, it's more about the many event listeners that will be attached to the existing DOM elements.

If possible I'd paginate those results anyway

**Comment by ericxin1982** [comment]
I see.
