### ISSUE TITLE
minimized css standalone, and do not use bootstrap css totally

### ISSUE THREAD

**Issue by ericxin1982** [ovesco/flyter#3]
HI @ovesco 

Is it possible, I can minimize a minimized css file for flyter, and do not include the whole bootstrap css file in, since I am scared of css class mixed trouble.

Thanks
Eric Xin

**Comment by ovesco** [comment]
Hello,

Flyter does not come with any CSS at all. The bootstrap theme simply adds bootstrap classes to the templates but if you don't load bootstrap by yourself it won't be styled.

**Comment by ericxin1982** [comment]
Ok, so I can take those used bootstrap class as standalone file, and load this small css file, that is ok to go also, right?

**Comment by ovesco** [comment]
Yes you can extract the corresponding classes from the bootstrap library and loading them will work
