### ISSUE TITLE
Feature Request: allow to configure popover container

### ISSUE THREAD

**Issue by blikblum** [ovesco/flyter#4]
When using the popover renderer, the popover markup is unconditionally added to body element: https://github.com/ovesco/flyter/blob/master/src/renderer/PopupRenderer.ts#L143

When using the popover renderer in a Bootstrap Modal, the Modal prevents the popover to receive focus.

Bootstrap allow to configure the container of the Popover: https://getbootstrap.com/docs/5.3/components/popovers/#custom-container

I managed to fix by moving the popover element in renderer.config.onInit:

```js
   const flyterInstance = flyter.attach(this.querySelector('[data-flyter]'), {
      initialValue: this.value,   
      renderer: {
        config: {
          onInit: (renderer) => {
            if (this.container) {
              const el = renderer.getMarkup()
              document.querySelector(this.container)?.appendChild(el)
            }
          },
        },
      },
    })
```

It works but required to hook into internals of flyter which may break in the future

**Comment by ovesco** [comment]
Thanks for bringing this up, I'll check it this week

**Comment by ovesco** [comment]
Pushed a new version, there is now a `popupContainer` option for the popup renderer which you can use to provide the container into which the popup markup will be inserted

**Comment by blikblum** [comment]
Many thanks

**Comment by blikblum** [comment]
Some notes:

There is a console.log call in getPopupContainer: https://github.com/ovesco/flyter/blob/master/src/renderer/PopupRenderer.ts#L226

The popupContainer table row in the docs is not rendered correct https://ovesco.github.io/flyter/config/type-and-renderer.html

**Comment by ovesco** [comment]
Sorry for that it's fixed 🙏🏻
